### ISSUE TITLE
Password change feature doesn't work

### ISSUE THREAD

**Issue by hampelm** [codeforamerica/Intersection#3]
Steps to reproduce:
1. Log in
2. Go to Profile
3. Click edit
4. Enter new password (note: password edit field is text, not password type)
5. Save 
6. Log out
7. Attempt to log in. Old password works, new password does not.

**Comment by prashtx** [comment]
Fixed the cleartext vs. password text issue with https://github.com/codeforamerica/Intersection/commit/93d70082965435fb3fbba833cac73b835cfadcc5

I am able to login with the new password.

Matt: do you still see the issue?

**Comment by ryanatwork** [comment]
Fixed in commit - https://github.com/codeforamerica/Intersection/commit/b258e985375493f0d5264784eb8321e2dbf823b8
