### ISSUE TITLE
Tabs on Team Page pulling wrong data

### ISSUE THREAD

**Issue by jlord** [codeforamerica/Intersection#4]
The Stories tab pulls Events and Events tab pulls Stories.

Whoot!

**Comment by prashtx** [comment]
It looks like the labels are just swapped in the team view. I'll fix that.

**Comment by ryanatwork** [comment]
Fixed on commit - https://github.com/codeforamerica/Intersection/commit/b3df60588f31f67582b4e7d3328b015268bfcae4

Thanks @prashtx

**Comment by prashtx** [comment]
Fixed with https://github.com/codeforamerica/Intersection/commit/b3df60588f31f67582b4e7d3328b015268bfcae4
